#! /bin/sh
# /etc/init.d/radio

### BEGIN INIT INFO
# Provides:          radio
# Required-Start:    mpd
# Required-Stop:     mpd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts radio via mpd
# Description:       Starts radio via mpd
### END INIT INFO

case "$1" in
  start)
    echo "Starting radio..."
    /home/pi/init_radio.sh
    ;;
  stop)
    echo "Stopped radio..."
    ;;
  *)
    echo "Usage: /etc/init.d/radio {start|stop}"
    exit 1
    ;;
esac

exit 0;
